<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>script</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GraphicNovelist</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.graphicnovelist</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.graphicnovelist</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.graphicnovelist</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([^:]*\:)?(\s*\(.*\))?(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.graphicnovelist</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.graphicnovelist</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(Panel \d*)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.graphicnovelist</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.graphicnovelist</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(@.*\:)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.graphicnovelist</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.graphicnovelist</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[.*].*)$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.graphicnovelist</string>
	<key>uuid</key>
	<string>DD9B1A57-1420-4398-96CA-71125FA534E0</string>
</dict>
</plist>
